name: Deploy Bot

on:
  push:
    branches:
      - main  # Change si ton repo utilise une autre branche

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18  # Mets la version correcte pour ton bot

      - name: Install Dependencies
        run: npm install

      - name: Start Bot
        run: node index.js  # Remplace par le fichier principal de ton bot
